`DbContext` + entity changes for ef
is-tech-y24-1/Do-Svyazi.Music pull request #28
Opened 2022-05-29 18:42 UTC by JabaJabila

## Type
- [x] new
- [ ] fix
- [ ] refactor

## Interface
- [ ] frontend
- [x] backend
- [ ] docs
- [ ] ci

closes #13

2022-05-29 18:43 UTC, JabaJabila commented
пока что сделал проект не как class library, а console application, чтобы попробовать погенерить sqlite. Потом поменяю на class library

2022-05-29 18:58 UTC, sashafromlibertalia requested changes

2022-05-29 18:58 UTC, sashafromlibertalia commented on Modules/DS.DataAccess/Context/MusicDbContext.cs
> +        // Database.EnsureDeleted();
коммент

2022-05-29 18:58 UTC, sashafromlibertalia commented on Modules/DS.DataAccess/IMusicContext.cs
> +    public DbSet<SongGenre> SongGenres { get; }
паблик и так по умолчанию

2022-05-29 19:01 UTC, JabaJabila commented on Modules/DS.DataAccess/IMusicContext.cs
> +    public DbSet<SongGenre> SongGenres { get; }
здесь упс...

2022-05-29 19:01 UTC, JabaJabila commented on Modules/DS.DataAccess/Context/MusicDbContext.cs
> +        // Database.EnsureDeleted();
а здесь рабочий момент, после того, как протестирую работоспособность - уберу

2022-05-30 15:04 UTC, sashafromlibertalia approved these changes

2022-05-30 21:55 UTC, Ssspook approved these changes

2022-05-31 04:08 UTC, merged