feat: First handlers implemented, Sasha's cringe removed, tiny signature refactor
is-tech-y24-1/Do-Svyazi.Music pull request #42
Opened 2022-06-01 19:53 UTC by Ssspook

Handlers implementation

## Type
- [x] new
- [ ] fix
- [ ] refactor

## Interface
- [ ] frontend
- [x] backend
- [ ] docs
- [ ] ci

**NB!** Эта срань пока не тестировалась на БД
closes #

2022-06-01 19:57 UTC, sashafromlibertalia requested changes

2022-06-01 19:57 UTC, sashafromlibertalia commented on Source/Application/DS.Application.CQRS/ListeningQueue/Commands/AddLastToQueue.cs
> +            var song = await _context.Songs.FindAsync(request.SongId);
А че будет если не найдёт?

2022-06-01 19:57 UTC, sashafromlibertalia commented on Source/Application/DS.Application.CQRS/ListeningQueue/Commands/DeleteSongFromQueue.cs
> +            listeningQueue?.RemoveSong(song!);
Точно «!» нужен?

2022-06-01 19:59 UTC, JabaJabila requested changes
Не, похоже на то, что я бы хотел видеть на данном этапе, но уж вообще никакой проверки на то, найдём мы или нет - нету. От этого ты и срёшь ? и !, а мог бы не срать

2022-06-01 19:59 UTC, JabaJabila commented on Source/Application/DS.Application.CQRS/ListeningQueue/Commands/AddLastToQueue.cs
> +            listeningQueue?.AddLastToPlay(song!);
Можна строки попропускать между блоками?

2022-06-01 20:00 UTC, sashafromlibertalia approved these changes

2022-06-01 20:01 UTC, Ssspook commented on Source/Application/DS.Application.CQRS/ListeningQueue/Commands/AddLastToQueue.cs
> +            var song = await _context.Songs.FindAsync(request.SongId);
См. описание ПР

2022-06-02 09:59 UTC, JabaJabila commented on Source/Application/DS.Application.CQRS/ListeningQueue/Commands/AddLastToQueue.cs
> +        public Handler(MusicDbContext context)
кстати, ток щас заметил. Есть саджест о зависимости не от самого контекста, а от интерфейса к нему IMusicContext. Там инкапсулировано то, что не должно торчать наружу при работе с просто контекстом

2022-06-02 16:22 UTC, sashafromlibertalia approved these changes

2022-06-02 21:01 UTC, sashafromlibertalia requested changes

2022-06-02 21:09 UTC, JabaJabila requested changes
Хэндлеры не смотрел особо (вроде норм), а к дтошкам есть вопросы

2022-06-02 21:23 UTC, Ssspook commented on Source/Application/DS.Application.CQRS/MediaLibrary/Commands/CreateNewSong.cs
> +            var song = new Domain.Song
обсудили в тг

2022-06-02 22:01 UTC, sashafromlibertalia submitted a review, later dismissed

2022-06-03 03:59 UTC, JabaJabila approved these changes

2022-06-03 08:30 UTC, sashafromlibertalia approved these changes

2022-06-03 08:34 UTC, JabaJabila approved these changes

2022-06-03 08:34 UTC, merged