feat: DTOs mapping
is-tech-y24-1/Do-Svyazi.Music pull request #48
Opened 2022-06-04 13:26 UTC by Ssspook

## Type
- [x] new
- [ ] fix
- [ ] refactor

## Interface
- [ ] frontend
- [x] backend
- [ ] docs
- [ ] ci

closes #
Прошу пристального внимания, мог насрать

2022-06-04 13:27 UTC, sashafromlibertalia requested changes

2022-06-04 13:27 UTC, sashafromlibertalia commented on Source/Application/DS.Application.CQRS/MediaLibrary/Queries/GetAuthoredSongs.cs
> +        private IMapper _mapper;
я мб не уверен, но их можно сделать ридонли

2022-06-04 13:27 UTC, sashafromlibertalia commented on Source/Application/DS.Application.CQRS/MediaLibrary/Queries/GetPlaylists.cs
> +        private IMapper _mapper;
аналогично (таких место много вроде)

2022-06-05 08:18 UTC, JabaJabila commented on Source/Application/DS.Application.CQRS/ListeningQueue/Queries/GetQueueInfo.cs
> +        private IMapper _mapper;
как уже было справедливо подмечено, и контекст и маппер лучше ридонли

2022-06-05 08:19 UTC, JabaJabila commented on Source/Application/DS.Application.CQRS/Mapping/DomainToResponse.cs
> +    }
ну уж можно было бы пустыми линиями поразделять

2022-06-05 08:20 UTC, JabaJabila commented on Source/Domain/DS.Domain/ListeningQueue.cs
>      public IReadOnlyCollection<Song> Songs => _songs;
списибо, что разъебал ef, теперь в контексте нужно указать, что OwnerId - первичный ключ

2022-06-05 17:17 UTC, JabaJabila approved these changes

2022-06-05 17:18 UTC, sashafromlibertalia approved these changes

2022-06-05 17:19 UTC, merged

2022-06-10 18:04 UTC, lipa44 commented on Source/Application/DS.Application.CQRS/Mapping/DomainToResponse.cs
> +    }
насрал